const cartActionTypes = {
  FETCH_ORDERS_START: 'FETCH_ORDERS_START',
  FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
  FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',
  ADD_ORDER_START: 'ADD_ORDER_START',
  ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
  ADD_ORDER_FAILURE: 'ADD_ORDER_FAILURE',
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_ALL_CART_ITEMS: 'CLEAR_ALL_CART_ITEMS',
  TOGGLE_CART_VISIBLE: 'TOGGLE_CART_VISIBLE'
}

export default cartActionTypes