const userActionTypes = {
  USER_LOG_IN_START: 'USER_LOG_IN_START',
  USER_LOG_IN_SUCCESS: 'USER_LOG_IN_SUCCESS',
  USER_LOG_IN_FAILURE: 'USER_LOG_IN_FAILURE',
  USER_LOG_OUT_START: 'USER_LOG_OUT_START',
  USER_LOG_OUT_SUCCESS: 'USER_LOG_OUT_SUCCESS',
  USER_LOG_OUT_FAILURE: 'USER_LOG_OUT_FAILURE',
  USER_SIGN_UP_START: 'USER_SIGN_UP_START',
  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE',
  EDIT_USER_START: 'EDIT_USER_START',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER_FAILURE'
}

export default userActionTypes