import productReducer from "./product.reducer"

const productActionTypes = {
  FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  FETCH_PRODUCT_TYPES_START: 'FETCH_PRODUCT_TYPES_START',
  FETCH_PRODUCT_TYPES_SUCCESS: 'FETCH_PRODUCT_TYPES_SUCCESS',
  FETCH_PRODUCT_TYPES_FAILURE: 'FETCH_PRODUCT_TYPES_FAILURE',
  EDIT_PRODUCT_START: 'EDIT_PRODUCT_START',
  EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
  EDIT_PRODUCT_FAILURE: 'EDIT_PRODUCT_FAILURE',
  DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
  ADD_PRODUCT_START: 'ADD_PRODUCT_START',
  ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
  CHANGE_CURRENCY: 'CHANGE_CURRENCY'
}

export default productActionTypes